---

- name: Install YUM dependencies
  yum:
    name: "{{ oel_packages }}"
    state: present
  register: log_output

- name: Update all packages
  yum:
    name: '*'
    state: latest
  ignore_errors: true