---

- name: Install YUM dependencies
  yum:
    name: "{{ oel_yum_packages }}"
    state: present

- name: Install DNF dependencies
  dnf:
    name: "{{ oel_dnf_packages }}"
    state: present

- name: Update all packages
  yum:
    name: '*'
    state: latest
  ignore_errors: true

- name: Update all packages
  dnf:
    name: '*'
    state: latest
  ignore_errors: true