---

- name: Configure operating system
  become: true
  hosts: localhost
  roles:
    - role: role-os-startup
    
- name: Create users
  become: true
  hosts: localhost
  roles:
    - role: role-user-creation

# - name: Wait for Terraform to mount all disks
#   become: true
#   hosts: localhost
#   roles:
#     - role: role-wait-mounts

- name: Mount disks
  become: true
  hosts: localhost
  roles:
    - role: role-mount-disks