---

- name: Find volumes for /sapdump only
  set_fact: 
    sapdump_devices: "{{ sapdump_devices | default([]) + [item['value']['device_name']] }}"
  when: item['value']['os_path_to_mount'] == '/sapdump'
  loop: "{{ ebs_input_map }}"

- name: Find volumes for /oracle/SID/sapdata only
  set_fact: 
    oracle_sapdata_devices: "{{ oracle_sapdata_devices | default([]) + [item['value']['device_name']] }}"
  when: item['value']['os_path_to_mount'] == oracle_sap_data_folder
  loop: "{{ ebs_input_map }}"

- name: Find volumes for /hana/data only
  set_fact: 
    hana_data_devices: "{{ hana_data_devices | default([]) + [item['value']['device_name']] }}"
  when: item['value']['os_path_to_mount'] == '/hana/data'
  loop: "{{ ebs_input_map }}"
