---

- name: Find oracle internal devices
  set_fact: 
    oracle_sapdata_internal_devices: "{{ oracle_sapdata_internal_devices | default([]) + [ '/dev/' + item.item ] }}"
  loop: "{{ mount_types_complete.results }}"
  when: item.stdout in oracle_sapdata_devices
  no_log: yes

- name: Add /oracle/SID/sapdata to the final list
  set_fact: 
    ebs_full_map: "{{ ebs_full_map | default([]) + [{ 'device_name' : oracle_sapdata_devices, 'internal_device': oracle_sapdata_internal_devices, 'os_path_to_mount': oracle_sap_data_folder }] }}"
  ignore_errors: yes
