---

D77_SID: D77
D76_SID: D76

D77_stripes_oracle: 1
D77_stripes_sapdata: 2
D77_stripes_mirrlog: 1
D77_stripes_origlog: 1

D76_stripes_oracle: 1
D76_stripes_sapdata: 2
D76_stripes_mirrlog: 1
D76_stripes_origlog: 1

oracle_lv_config:
  - key: D77
    value:
      - folder: /oracle
        vg: vg_oracle
        size: 5G
        name: lv_oracle
        stripes: "{{ D77_stripes_oracle }}"
      - folder: /oracle/stage
        vg: vg_oracle
        size: 40G
        name: lv_oracle_stage
        stripes: "{{ D77_stripes_oracle }}"
      - folder: /oracle/{{ D77_SID }}
        vg: vg_oracle
        size: 50G
        name: lv_oracle_sid
        stripes: "{{ D77_stripes_oracle }}"
      - folder: /oracle/{{ D77_SID }}/oraarch
        vg: vg_oracle
        size: 20G
        name: lv_oracle_sid_oraarch
        stripes: "{{ D77_stripes_oracle }}"
      - folder: /oracle/{{ D77_SID }}/sapreorg
        vg: vg_oracle
        size: 50G
        name: lv_oracle_sid_sapreorg
        stripes: "{{ D77_stripes_oracle }}"
      - folder: /oracle/{{ D77_SID }}/origlogA
        vg: vg_oracle_sid_origlog
        size: 5G
        name: lv_oracle_sid_origlogA
        stripes: "{{ D77_stripes_origlog }}"
      - folder: /oracle/{{ D77_SID }}/origlogB
        vg: vg_oracle_sid_origlog
        size: 5G
        name: lv_oracle_sid_origlogB
        stripes: "{{ D77_stripes_origlog }}"
      - folder: /oracle/{{ D77_SID }}/mirrlogA
        vg: vg_oracle_sid_mirrlog
        size: 5G
        name: lv_oracle_sid_mirrlogA
        stripes: "{{ D77_stripes_mirrlog }}"
      - folder: /oracle/{{ D77_SID }}/mirrlogB
        vg: vg_oracle_sid_mirrlog
        size: 5G
        name: lv_oracle_sid_mirrlogB
        stripes: "{{ D77_stripes_mirrlog }}"
      - folder: /oracle/{{ D77_SID }}/sapdata1
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata1
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata2
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata2
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata3
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata3
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata4
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata4
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata5
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata5
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata6
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata6
        stripes: "{{ D77_stripes_sapdata }}"
      - folder: /oracle/{{ D77_SID }}/sapdata7
        vg: vg_oracle_sid_sapdata
        size: 150G
        name: lv_oracle_sid_sapdata7
        stripes: "{{ D77_stripes_sapdata }}"
  - key: D76
    value:
      - folder: /oracle
        vg: vg_oracle
        size: 5G
        name: lv_oracle
        stripes: "{{ D76_stripes_oracle }}"
      - folder: /oracle/stage
        vg: vg_oracle
        size: 40G
        name: lv_oracle_stage
        stripes: "{{ D76_stripes_oracle }}"
      - folder: /oracle/{{ D76_SID }}
        vg: vg_oracle
        size: 50G
        name: lv_oracle_sid
        stripes: "{{ D76_stripes_oracle }}"
      - folder: /oracle/{{ D76_SID }}/oraarch
        vg: vg_oracle
        size: 20G
        name: lv_oracle_sid_oraarch
        stripes: "{{ D76_stripes_oracle }}"
      # - folder: /oracle/{{ D76_SID }}/saparch
      #   vg: vg_oracle
      #   size: 4G
      #   name: lv_oracle_sid_saparch
      #   stripes: "{{ D76_stripes_oracle }}"
      - folder: /oracle/{{ D76_SID }}/sapreorg
        vg: vg_oracle
        size: 50G
        name: lv_oracle_sid_sapreorg
        stripes: "{{ D76_stripes_oracle }}"
      - folder: /oracle/{{ D76_SID }}/origlogA
        vg: vg_oracle_sid_origlog
        size: 5G
        name: lv_oracle_sid_origlogA
        stripes: "{{ D76_stripes_origlog }}"
      - folder: /oracle/{{ D76_SID }}/origlogB
        vg: vg_oracle_sid_origlog
        size: 5G
        name: lv_oracle_sid_origlogB
        stripes: "{{ D76_stripes_origlog }}"
      # - folder: /oracle/{{ D76_SID }}/origlogC
      #   vg: vg_oracle_sid_origlog
      #   size: 4G
      #   name: lv_oracle_sid_origlogC
      #   stripes: "{{ D76_stripes_origlog }}"
      # - folder: /oracle/{{ D76_SID }}/origlogD
      #   vg: vg_oracle_sid_origlog
      #   size: 4G
      #   name: lv_oracle_sid_origlogD
      #   stripes: "{{ D76_stripes_origlog }}"
      - folder: /oracle/{{ D76_SID }}/mirrlogA
        vg: vg_oracle_sid_mirrlog
        size: 5G
        name: lv_oracle_sid_mirrlogA
        stripes: "{{ D76_stripes_mirrlog }}"
      - folder: /oracle/{{ D76_SID }}/mirrlogB
        vg: vg_oracle_sid_mirrlog
        size: 5G
        name: lv_oracle_sid_mirrlogB
        stripes: "{{ D76_stripes_mirrlog }}"
      # - folder: /oracle/{{ D76_SID }}/mirrlogC
      #   vg: vg_oracle_sid_mirrlog
      #   size: 4G
      #   name: lv_oracle_sid_mirrlogC
      #   stripes: "{{ D76_stripes_mirrlog }}"
      # - folder: /oracle/{{ D76_SID }}/mirrlogD
      #   vg: vg_oracle_sid_mirrlog
      #   size: 4G
      #   name: lv_oracle_sid_mirrlogD
      #   stripes: "{{ D76_stripes_mirrlog }}"
      - folder: /oracle/{{ D76_SID }}/sapdata1
        vg: vg_oracle_sid_sapdata
        size: 80G
        name: lv_oracle_sid_sapdata1
        stripes: "{{ D76_stripes_sapdata }}"
      - folder: /oracle/{{ D76_SID }}/sapdata2
        vg: vg_oracle_sid_sapdata
        size: 80G
        name: lv_oracle_sid_sapdata2
        stripes: "{{ D76_stripes_sapdata }}"
      - folder: /oracle/{{ D76_SID }}/sapdata3
        vg: vg_oracle_sid_sapdata
        size: 80G
        name: lv_oracle_sid_sapdata3
        stripes: "{{ D76_stripes_sapdata }}"
      - folder: /oracle/{{ D76_SID }}/sapdata4
        vg: vg_oracle_sid_sapdata
        size: 80G
        name: lv_oracle_sid_sapdata4
        stripes: "{{ D76_stripes_sapdata }}"
