---

groups_to_create:
  - name: sapsys
    gid: 200
  - name: dba
    gid: 201
  - name: oper
    gid: 202
  - name: sapinst
    gid: 2000
  - name: oinstall
    gid: 54321

users_to_create:
  - name: daaadm
    uid: 3098
    primary_group: sapsys
    groups: sapsys
  - name: sapadm
    uid: 3099
    primary_group: sapsys
    groups: sapsys
  - name: oracle
    uid: 54321
    primary_group: oinstall
    groups: dba, oper
  - name: oras76
    uid: 4377
    primary_group: sapsys
    groups: dba,oper,oinstall
  - name: s76adm
    uid: 4376
    primary_group: sapsys
    groups: sapsys,sapinst
  - name: s71adm
    uid: 4371
    groups: sapsys,sapinst