---

groups_to_create:
  - name: sapsys
    gid: 200
  - name: dba
    gid: 201
  - name: oper
    gid: 202
  - name: sapinst
    gid: 2000
  - name: oinstall
    gid: 54321

users_to_create:
  - name: daaadm
    uid: 3198
    primary_group: sapsys
    groups: sapsys
  - name: sapadm
    uid: 3199
    primary_group: sapsys
    groups: sapsys
  - name: oracle
    uid: 54321
    primary_group: oinstall
    groups: dba,oper
  - name: orad77
    uid: 3277
    primary_group: dba
    groups: dba,oper,oinstall
  - name: d77adm
    uid: 3278
    primary_group: sapsys
    groups: sapsys,sapinst
  - name: d70adm
    uid: 3270
    primary_group: sapsys
    groups: sapsys,sapinst
