---

GLOBAL_ENVIRONMENT: "{{ INPUT_ENVIRONMENT | default('predev') }}"

GLOBAL_OS_CONFIG_TYPE: "{{ INPUT_OS_CONFIG_TYPE | default('NETWEAVER') }}"
GLOBAL_OS_TYPE: "{{ INPUT_OS_TYPE | default('RHEL8.8') }}"

GLOBAL_AWS_REGION: "{{ INPUT_AWS_REGION }}"

GLOBAL_EFS_ACCESS_POINT_ID: "{{ INPUT_EFS_ACCESS_POINT_ID }}"
GLOBAL_EFS_ID: "{{ INPUT_EFS_ID }}"

GLOBAL_HOSTNAME: "{{ INPUT_HOSTNAME }}"
GLOBAL_HOSTNAME_FQDN: "{{ INPUT_HOSTNAME_FQDN }}"

CONSTANT_HANA: "HANA"
CONSTANT_NETWEAVER: "NETWEAVER"
CONSTANT_ORACLE: "ORACLE"

CONSTANT_OEL_8_8: "OEL8.8"
CONSTANT_RHEL_8_8: "RHEL8.8"