repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.44.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args: ['--envs=AWS_DEFAULT_REGION="ca-central-1']
    - id: terraform_tflint
    - id: terraform_docs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-merge-conflict
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [ --branch, main]
