environment                = "pdev"
aws_region                 = "ca-central-1"
app_name                   = "retail"
kms_key_arn                = ""
s3_buckets_ec2_image_builder_logs = "bell-tests-tf"