---

- name: Create and activate sap-netweaver profile
  command: "{{ item }}"
  loop:
    - sysctl --system
    - tuned --daemon
    # - tuned-adm profile sap-netweaver
    - tuned-adm active
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_NETWEAVER