---

- name: Make sure efs-utils is not present
  file:
    path: /tmp/efs-utils
    state: absent

- name: Clone efs-utils repo
  command: git clone https://github.com/aws/efs-utils /tmp/efs-utils

- name: Make rpm
  command: make clean rpm
  args:
    chdir: /tmp/efs-utils

- name: Find generated RPM file
  find:
    paths: /tmp/efs-utils/build
    file_type: file
    use_regex: yes
    patterns:
      - '^amazon-efs-utils_.*.rpm$'
  register: found_rpm_file

- name: List files
  debug:
    msg: "{{ found_rpm_file }}"

# - name: Install amazon-efs-utils
#   yum:
#     name: "/tmp/efs-utils/build/amazon-efs-utils*rpm"
#     state: present