---

- name: Make sure efs-utils is not present
  file:
    path: /tmp/efs-utils
    state: absent

- name: Clone efs-utils repo
  command: git clone https://github.com/aws/efs-utils /tmp/efs-utils

- name: Make rpm
  make:
    chdir: /tmp/efs-utils

- name: Install amazon-efs-utils
  yum:
    name: "/tmp/efs-utils/build/amazon-efs-utils*rpm"
    state: present