---

- name: Install dependencies for RedHat
  include_tasks: install_rhel_deps.yaml
  when: ansible_os_family == "RedHat"

- name: Check if AWS CLI is available
  include_tasks: common/check_aws_cli.yaml

- name: Install AWS SSM
  include_tasks: install_ssm.yaml

- name: Install AWS SAP Data Provider for RedHat
  include_tasks: rhel/install_data_provider_rhel.yaml
  when: ansible_os_family == "RedHat"