---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Check if all required disks are attached for {{ CONSTANT_HANA }}
  set_fact: filtered_disks="{{ ansible_devices | map('regex_search', '^' + regex_to_look_for_disks ) | select ('string') | list }}"
  failed_when: "filtered_disks | length < hana_minimum_number_of_mounted_disks_to_search"
  retries: 60
  delay: 5
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_HANA

- name: Check if all required disks are attached for {{ CONSTANT_NETWEAVER }}
  set_fact: filtered_disks="{{ ansible_devices | map('regex_search', '^' + regex_to_look_for_disks ) | select ('string') | list }}"
  failed_when: "filtered_disks | length < netweaver_minimum_number_of_mounted_disks_to_search"
  retries: 60
  delay: 5
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_NETWEAVER

- name: Check if all required disks are attached for {{ CONSTANT_ORACLE }}
  set_fact: filtered_disks="{{ ansible_devices | map('regex_search', '^' + regex_to_look_for_disks ) | select ('string') | list }}"
  failed_when: "filtered_disks | length < oracle_minimum_number_of_mounted_disks_to_search"
  retries: 60
  delay: 5
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_ORACLE