---

- name: Create directories for EBS if they don't exist
  file:
    path: "{{ item['os_path_to_mount'] }}"
    state: directory
    mode: '0755'
  when: item['os_path_to_mount'] != ''
  loop: "{{ ebs_full_map }}"