---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Show vars
  debug:
    msg: "{{ folders_to_create }}"  

- name: Create folders
  include_tasks: create_folders.yaml

- name: Check if all disks are attached
  include_tasks: check_all_disks_are_attached.yaml

- name: Check if disks are mounted
  include_tasks: check_disks_are_mounted.yaml

- name: Mount disks
  include_tasks: mount_disks.yaml
  when: all_disks_mounted is not defined or all_disks_mounted|bool == false