---

- name: Mount EFS
  include_tasks: mount_efs.yaml
  when: INPUT_REQUIRED_EFS_TO_MOUNT is defined

- name: Waits for 3 minute to give Terraform the time to mount EBS volumes properly
  pause:
    minutes: 3

- name: Mount EBS
  include_tasks: mount_ebs.yaml
  when: INPUT_EBS_MAP_TO_MOUNT is defined