---

- name: Mount EFS
  include_tasks: mount_efs.yaml
  when: INPUT_REQUIRED_EFS_TO_MOUNT is defined
  
- name: Create custom oracle folders
  include_tasks: create_oracle_folders.yaml
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_ORACLE

- name: Mount EBS
  include_tasks: mount_ebs.yaml
  when: INPUT_EBS_MAP_TO_MOUNT is defined