---

- name: Parse input params
  include_tasks: parse_input/parse_input.yaml

- name: Create folders
  include_tasks: create_folders.yaml

- name: Mount common EBS
  include_tasks: mount_ebs_common.yaml

- name: Mount Oracle EBS
  include_tasks: mount_ebs_oracle.yaml
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_ORACLE
