---

- name: Parse input JSON into dict
  set_fact: mounts_map="{{ INPUT_REQUIRED_EFS_TO_MOUNT | from_yaml | dict2items }}"

- name: Show EFS volumes to mount
  debug:
    msg: "{{ item }}"
  loop: "{{ mounts_map }}"

- name: Ensure EFS folders are created
  file:
    path: "{{ item['value']['full_path'] }}"
    state: directory
    mode: '0755'
  loop: "{{ mounts_map }}"

- name: Ensure EFS volumes are mounted
  mount:
    name: "{{ item['value']['full_path'] }}"
    src: "{{ item['value']['efs_id'] }}{{ ':/' + item['value']['folder_on_efs_to_mount'] | default('', true) }}"
    fstype: efs
    opts: "_netdev,tls,mounttargetip={{ item['value']['mount_target_ip'] }}"
    state: mounted
    dump: "0"
    passno: "2"
  loop: "{{ mounts_map }}"
