---

- name: Ensure EFS volume is mounted.
  mount:
    name: "{{ sapmnt_folder }}"
    src: "{{ GLOBAL_EFS_ID }}.efs.{{ GLOBAL_AWS_REGION }}.amazonaws.com:/"
    fstype: efs
    opts: "_netdev,tls,accesspoint={{ GLOBAL_EFS_ACCESS_POINT_ID }}"
    state: mounted