---

- name: Show variables received as input parameters
  include_tasks: common/show_input_variables.yaml

- name: Set tuned
  include_tasks: common/set_tuned.yaml

- name: Set hostname
  include_tasks: common/set_instance_hostname.yaml