---

- name: Show variables received as input parameters
  include_tasks: common/validate_and_show_input_variables.yaml

- name: Set tuned
  include_tasks: common/set_tuned.yaml
  when:
    - GLOBAL_OS_CONFIG_TYPE != CONSTANT_ORACLE
    - GLOBAL_OS_TYPE != CONSTANT_OEL_8_7

- name: Set hostname
  include_tasks: common/set_instance_hostname.yaml

- name: Start UUIDD
  include_tasks: common/start_uuidd.yaml