---

- name: Validate variables received as input parameters
  include_tasks: common/validate_input_variables.yaml

- name: Show variables received as input parameters
  include_tasks: common/show_input_variables.yaml

- name: Remove proxy configurations
  include_tasks: common/remove_proxy.yaml

- name: Set tuned
  include_tasks: common/set_tuned.yaml
  when:
    - GLOBAL_OS_CONFIG_TYPE != CONSTANT_ORACLE
    - GLOBAL_OS_TYPE != CONSTANT_OEL_8_8

- name: Set hostname
  include_tasks: common/set_instance_hostname.yaml

- name: Start UUIDD
  include_tasks: common/start_uuidd.yaml

- name: Disable iptables service
  include_tasks: oel/disable_iptables.yaml
  when: ansible_distribution == "OracleLinux"

- name: Apply NetWeaver kernel semaphore parameters
  include_tasks: netweaver/kernel_parameters.yaml
  when: GLOBAL_OS_CONFIG_TYPE == CONSTANT_NETWEAVER
