---

groups_to_create:
  - name: sapsys
    gid: 200
  - name: dba
    gid: 201
  - name: oper
    gid: 202
  - name: sapinst
    gid: 203 # TODO: confirm which gid to use here
  - name: oinstall
    gid: 54321

users_to_create:
  - name: daaadm
    uid: 3098
    groups: dba, oper # TODO: confirm which groups to use here
  - name: sapadm
    uid: 3099
    groups: sapsys, sapinst # TODO: confirm which groups to use here

users_to_create_with_primary_group:
  - name: oracle
    uid: 54321
    primary_group: oinstall
    groups: dba, oper