---

# Variables to check disks mounted
regex_to_look_for_disks: "nvme\\w*n1\\b"

grep_find_command: grep /dev/xvd
awk_position_command: awk '{ print $18 }'
sed_replace_command: sed -e 's/"//g' -e 's/\.*//g'

disk_mapping_folder:
  - key: swap
    value:
      vg: vg_swap
      lv: lv_swap
  - key: /tmp
    value:
      vg: vg_tmp
      lv: lv_tmp
  - key: /usr/sap
    value: 
      vg: vg_usrsap
      lv: lv_usrsap
  - key: /usr/sap/DAA
    value:
      vg: vg_usr_sap_daa
      lv: lv_usr_sap_daa
  - key: /SAPCD
    value:
      vg: vg_sapcd
      lv: lv_sapcd
  - key: /opt/IBM/tws930
    value:
      vg: vg_opt_ibm_tws930
      lv: lv_opt_ibm_tws930
  - key: /usr/Tivoli
    value:
      vg: vg_usr_tivoli
      lv: lv_usr_tivoli
  - key: /etc/Tivoli
    value:
      vg: vg_etc_tivoli
      lv: lv_etc_tivoli
  - key: /hana/data
    value:
      vg: vg_hana_data
      lv: lv_hana_data
  - key: /hana/log
    value:
      vg: vg_hana_log
      lv: lv_hana_log
  - key: /hana/shared
    value:
      vg: vg_hana_shared
      lv: lv_hana_shared 
  - key: /backup
    value:
      vg: vg_hana_backup
      lv: lv_hana_backup
  - key: /oracle
    value:
      vg: vg_oracle
      lv: lv_oracle
  - key: /oracle/stage
    value:
      vg: vg_oracle_stage
      lv: lv_oracle_stage
  - key: /oracle/SID
    value:
      vg: vg_oracle_sid
      lv: lv_oracle_sid
  - key: /oracle/SID/origlogA
    value:
      vg: vg_oracle_sid_origlogA
      lv: lv_oracle_sid_origlogA
  - key: /oracle/SID/origlogB
    value:
      vg: vg_oracle_sid_origlogB
      lv: lv_oracle_sid_origlogB
  - key: /oracle/SID/origlogC
    value:
      vg: vg_oracle_sid_origlogC
      lv: lv_oracle_sid_origlogC
  - key: /oracle/SID/mirrlogA
    value:
      vg: vg_oracle_sid_mirrlogA
      lv: lv_oracle_sid_mirrlogA
  - key: /oracle/SID/mirrlogB
    value:
      vg: vg_oracle_sid_mirrlogB
      lv: lv_oracle_sid_mirrlogB
  - key: /oracle/SID/mirrlogC
    value:
      vg: vg_oracle_sid_mirrlogC
      lv: lv_oracle_sid_mirrlogC
  - key: /oracle/SID/sapreorg
    value:
      vg: vg_oracle_sid_sapreorg
      lv: lv_oracle_sid_sapreorg
  - key: /oracle/SID/oraarch
    value:
      vg: vg_oracle_sid_oraarch
      lv: lv_oracle_sid_oraarch
  - key: /oracle/SID/sapdata1
    value:
      vg: vg_oracle_sid_sapdata1
      lv: lv_oracle_sid_sapdata1
  - key: /oracle/SID/sapdata2
    value:
      vg: vg_oracle_sid_sapdata2
      lv: lv_oracle_sid_sapdata2
  - key: /oracle/SID/sapdata3
    value:
      vg: vg_oracle_sid_sapdata3
      lv: lv_oracle_sid_sapdata3
  - key: /oracle/SID/sapdata4
    value:
      vg: vg_oracle_sid_sapdata4
      lv: lv_oracle_sid_sapdata4
  - key: /oracle/SID/sapdata5
    value:
      vg: vg_oracle_sid_sapdata5
      lv: lv_oracle_sid_sapdata5
  - key: /oracle/SID/sapdata6
    value:
      vg: vg_oracle_sid_sapdata6
      lv: lv_oracle_sid_sapdata6
  - key: /oracle/SID/sapdata7
    value:
      vg: vg_oracle_sid_sapdata7
      lv: lv_oracle_sid_sapdata7
  - key: /oracle/SID/sapdata8
    value:
      vg: vg_oracle_sid_sapdata8
      lv: lv_oracle_sid_sapdata8
  - key: /oracle/SID/sapdata9
    value:
      vg: vg_oracle_sid_sapdata9
      lv: lv_oracle_sid_sapdata9
  - key: /oracle/SID/sapdata10
    value:
      vg: vg_oracle_sid_sapdata10
      lv: lv_oracle_sid_sapdata10
  - key: /oracle/SID/sapdata11
    value:
      vg: vg_oracle_sid_sapdata11
      lv: lv_oracle_sid_sapdata11
  - key: /oracle/SID/sapdata12
    value:
      vg: vg_oracle_sid_sapdata12
      lv: lv_oracle_sid_sapdata12

hana_data_disk_type_pattern:
  - xvdf
  - xvdg
  - xvdh
hana_log_disk_type_pattern:
  - xvdm
  - xvdn
hana_shared_disk_type_pattern:
  - xvdo
hana_backup_disk_type_pattern:
  - xvdp

# Variables for mounting SWAP disks
hana_swap: /swap
volume_group_hana_swap: vg_swap
logical_volume_hana_swap: lv_swap

hana_swap_disk_type_pattern:
  - xvdr