---

# Variables to check disks mounted
regex_to_look_for_disks: "nvme\\w*n1\\b"

grep_find_command: grep /dev/xvd
awk_position_command: awk '{ print $18 }'
sed_replace_command: sed -e 's/"//g' -e 's/\.*//g'

disk_mapping_folder:
  - key: swap
    value:
      vg: vg_swap
      lv: lv_swap
  - key: /tmp
    value:
      vg: vg_tmp
      lv: lv_tmp
  - key: /usr/sap
    value: 
      vg: vg_usrsap
      lv: lv_usrsap
  - key: /usr/sap/DAA
    value:
      vg: vg_usr_sap_daa
      lv: lv_usr_sap_daa
  - key: /SAPCD
    value:
      vg: vg_sapcd
      lv: lv_sapcd
  - key: /opt/IBM/tws930
    value:
      vg: vg_opt_ibm_tws930
      lv: lv_opt_ibm_tws930
  - key: /usr/Tivoli
    value:
      vg: vg_usr_tivoli
      lv: lv_usr_tivoli
  - key: /etc/Tivoli
    value:
      vg: vg_etc_tivoli
      lv: lv_etc_tivoli
  - key: /hana/data
    value:
      vg: vg_hana_data
      lv: lv_hana_data
  - key: /hana/log
    value:
      vg: vg_hana_log
      lv: lv_hana_log
  - key: /hana/shared
    value:
      vg: vg_hana_shared
      lv: lv_hana_shared 
  - key: /hana/backup
    value:
      vg: vg_hana_backup
      lv: lv_hana_backup
  - key: /oracle
    value:
      vg: vg_oracle
      lv: lv_oracle
  - key: /oracle/{{ GLOBAL_SID }}/sapdata
    value:
      vg: vg_oracle_sid_sapdata
      lv: lv_oracle_sid_sapdata
  - key: /oracle/{{ GLOBAL_SID }}/origlog
    value:
      vg: vg_oracle_sid_origlog
      lv: lv_oracle_sid_origlog
  - key: /oracle/{{ GLOBAL_SID }}/mirrlog
    value:
      vg: vg_oracle_sid_mirrlog
      lv: lv_oracle_sid_mirrlog
  - key: /sapdump
    value:
      vg: vg_sapdump
      lv: lv_sapdump
  - key: /usr/sap/SMP
    value:
      vg: vg_usr_sap_smp
      lv: lv_usr_sap_smp

oracle_sap_data_folder: /oracle/{{ GLOBAL_SID }}/sapdata

oracle_folders_to_create:
  - /oracle
  - /oracle/stage
  - /oracle/{{ GLOBAL_SID }}
  - /oracle/{{ GLOBAL_SID }}/origlogA
  - /oracle/{{ GLOBAL_SID }}/origlogB
  - /oracle/{{ GLOBAL_SID }}/origlogC
  - /oracle/{{ GLOBAL_SID }}/mirrlogA
  - /oracle/{{ GLOBAL_SID }}/mirrlogB
  - /oracle/{{ GLOBAL_SID }}/mirrlogC
  - /oracle/{{ GLOBAL_SID }}/sapreorg
  - /oracle/{{ GLOBAL_SID }}/oraarch
  - /oracle/{{ GLOBAL_SID }}/sapdata1
  - /oracle/{{ GLOBAL_SID }}/sapdata2
  - /oracle/{{ GLOBAL_SID }}/sapdata3
  - /oracle/{{ GLOBAL_SID }}/sapdata4
  - /oracle/{{ GLOBAL_SID }}/sapdata5
  - /oracle/{{ GLOBAL_SID }}/sapdata6
  - /oracle/{{ GLOBAL_SID }}/sapdata7
  - /oracle/{{ GLOBAL_SID }}/sapdata8
  - /oracle/{{ GLOBAL_SID }}/sapdata9
  - /oracle/{{ GLOBAL_SID }}/sapdata10
  - /oracle/{{ GLOBAL_SID }}/sapdata11
  - /oracle/{{ GLOBAL_SID }}/sapdata12  

hana_data_disk_type_pattern:
  - xvdf
  - xvdg
  - xvdh
hana_log_disk_type_pattern:
  - xvdm
  - xvdn
hana_shared_disk_type_pattern:
  - xvdo
hana_backup_disk_type_pattern:
  - xvdp

# Variables for mounting SWAP disks
hana_swap: /swap
volume_group_hana_swap: vg_swap
logical_volume_hana_swap: lv_swap

hana_swap_disk_type_pattern:
  - xvdr
