---

# Variables to check disks mounted
regex_to_look_for_disks: "nvme\\w*n1\\b"

grep_find_command: grep /dev/xvd
awk_position_command: awk '{ print $18 }'
sed_replace_command: sed -e 's/"//g' -e 's/\.*//g'

disk_mapping_folder:
  - key: /tmp
    value:
      vg: vg_tmp
      lv: lv_tmp
  - key: /usr/sap
    value: 
      vg: vg_usrsap
      lv: lv_usrsap
  - key: /usr/sap/DAA
    value:
      vg: vg_usr_sap_daa
      lv: lv_usr_sap_daa
  - key: /SAPCD
    value:
      vg: vg_sapcd
      lv: lv_sapcd
  - key: /opt/IBM/tws930
    value:
      vg: vg_opt_ibm_tws930
      lv: lv_opt_ibm_tws930
  - key: /usr/Tivoli
    value:
      vg: vg_usr_tivoli
      lv: lv_usr_tivoli
  - key: /etc/Tivoli
    value:
      vg: vg_etc_tivoli
      lv: lv_etc_tivoli
  - key: /hana/data
    value:
      vg: vg_hana_data
      lv: lv_hana_data
  - key: /hana/log
    value:
      vg: vg_hana_log
      lv: lv_hana_log
  - key: /hana/shared
    value:
      vg: vg_hana_shared
      lv: lv_hana_shared 
  - key: /backup
    value:
      vg: vg_hana_backup
      lv: lv_hana_backup

hana_data_disk_type_pattern:
  - xvdf
  - xvdg
  - xvdh
hana_log_disk_type_pattern:
  - xvdm
  - xvdn
hana_shared_disk_type_pattern:
  - xvdo
hana_backup_disk_type_pattern:
  - xvdp

# Variables for mounting SWAP disks
hana_swap: /swap
volume_group_hana_swap: vg_swap
logical_volume_hana_swap: lv_swap

hana_swap_disk_type_pattern:
  - xvdr