---

- name: Ensure default groups are created
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  loop: "{{ default_groups_to_create }}"
  when: default_groups_to_create is defined

- name: Ensure sidadm groups are created
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
  loop: "{{ sidadm_groups_to_create }}"
  when: sidadm_groups_to_create is defined