---

- name: Ensure default users are created
  user:
    name: "{{ item.name }}"
    state: present
    uid: "{{ item.uid }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.groups }}"
  loop: "{{ users_to_create }}"
  when: users_to_create is defined

- name: Change shell to C Shell for Netweaver
  become: true
  user:
      name: "{{ item.name }}"
      shell: /bin/csh
  loop: "{{ users_to_create }}"
  when: users_to_create is defined and GLOBAL_OS_CONFIG_TYPE == CONSTANT_NETWEAVER
