---

- name: Ensure default users are created
  user:
    name: "{{ item.name }}"
    state: present
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
  loop: "{{ default_users_to_create }}"
  when: default_users_to_create is defined

- name: Ensure default users are created
  user:
    name: "{{ item.name }}"
    state: present
    uid: "{{ item.uid }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.groups }}"
  loop: "{{ default_users_to_create_with_primary_group }}"
  when: default_users_to_create_with_primary_group is defined

- name: Ensure sidadm users are created
  user:
    name: "{{ item.name }}"
    state: present
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
  loop: "{{ sidadm_users_to_create }}"
  when: sidadm_users_to_create is defined