---

- name: Include users and groups for "{{ INPUT_ENVIRONMENT }}" environment
  include_vars: "defaults/{{ INPUT_ENVIRONMENT }}/{{ GLOBAL_HOSTNAME }}.yaml"

- name: Create groups
  include_tasks: create_groups.yaml

- name: Create users
  include_tasks: create_users.yaml