---

- name: Include users and groups to be created for "{{ INPUT_ENVIRONMENT }}" environment and "{{ GLOBAL_HOSTNAME }}" hostname
  include_vars: "defaults/{{ INPUT_ENVIRONMENT }}/{{ GLOBAL_HOSTNAME }}.yaml"

- name: Create groups
  include_tasks: create_groups.yaml

- name: Create users
  include_tasks: create_users.yaml
