---

- name: Ensure mount directory exists
  file:
    path: "{{ sapmnt_dir }}"
    state: directory
    mode: 0755

# - name: Ensure EFS volume is mounted.
#   mount:
#     name: "{{ sapmnt_dir }}"
#     src: "{{ GLOBAL_EFS_ID }}.efs.{{ GLOBAL_AWS_REGION }}.amazonaws.com:/"
#     fstype: efs
#     opts: "tls,iam,accesspoint={{ GLOBAL_EFS_ACCESS_POINT_ID }}"
#     state: mounted

- name: Ensure EFS volume is mounted
  command: "mount -t efs -o tls,accesspoint={{ GLOBAL_EFS_ACCESS_POINT_ID }} {{ GLOBAL_EFS_ID }} {{ sapmnt_dir }}"