---

- name: Ensure mount directory exists
  file:
    path: "{{ sapmnt_dir }}"
    state: directory
    mode: 0755

- name: Ensure EFS volume is mounted.
  mount:
    name: "{{ sapmnt_dir }}"
    src: "{{ GLOBAL_EFS_ACCESS_POINT_ID }}.{{ GLOBAL_EFS_ID }}.efs.{{ GLOBAL_AWS_REGION }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1
    state: mounted

# Print the contents of the mount to the log.
- command: "ls -lah {{ efs_mount_dir }}"
  register: efs_contents
- debug: var=efs_contents