---

- name: Show input parameters
  debug:
    msg: "{{ item }}"
  loop:
    - "{{ INPUT_AWS_REGION }}"
    - "{{ INPUT_OS_CONFIG_TYPE }}"
    - "{{ INPUT_OS_TYPE }}"
    - "{{ INPUT_SID }}"
    - "{{ INPUT_HOSTNAME }}"
    - "{{ INPUT_HOSTNAME_FQDN }}"
    - "{{ INPUT_ENVIRONMENT }}"
    - "{{ INPUT_REQUIRED_EFS_TO_MOUNT | from_yaml }}"
    - "{{ INPUT_EBS_MAP_TO_MOUNT | from_yaml }}"
