---

- name: Halt execution if ENVIRONMENT is not found
  fail:
    msg: "The input parameter INPUT_ENVIRONMENT is not informed. Please check it and try again"
  when: not INPUT_ENVIRONMENT is defined

- name: Halt execution if REGION is not found
  fail:
    msg: "The input parameter INPUT_AWS_REGION is not informed. Please check it and try again"
  when: not INPUT_AWS_REGION is defined

- name: Halt execution if OS CONFIG TYPE is not found
  fail:
    msg: "The input parameter INPUT_OS_CONFIG_TYPE is not informed. Please check it and try again"
  when: not INPUT_OS_CONFIG_TYPE is defined

- name: Halt execution if OS TYPE is not found
  fail:
    msg: "The input parameter INPUT_OS_TYPE is not informed. Please check it and try again"
  when: not INPUT_OS_TYPE is defined

- name: Halt execution if EFS REQUIRED MOUNTS is not found
  fail:
    msg: "The input parameter INPUT_REQUIRED_EFS_TO_MOUNT is not informed. Please check it and try again"
  when: not INPUT_REQUIRED_EFS_TO_MOUNT is defined

- name: Halt execution if HOSTNAME is not found
  fail:
    msg: "The input parameter INPUT_HOSTNAME is not informed. Please check it and try again"
  when: not INPUT_HOSTNAME is defined